[package]
name = "rouvens-arch-kickstart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
ureq = "2.6"
regex = "1.8.1"
dirs = "5.0.0"
eframe = "0.21.3"
env_logger = "0.10.0"

[dev-dependencies]
assertor = "0.0"
pretty_assertions = "1.3"