[package]
name = "rouvens-arch-kickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
eframe = "0.22.0"
env_logger = "0.10.0"
ureq = "2.6"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
strip = true # Strip debug symbols
